### ISSUE TITLE
Two-digit index of ordered list is hidden when export to PDF

### ISSUE THREAD

**Issue by SignorMercurio** [andredelft/typora-tailwind-theme#10]
Thanks for the great theme! I'm reporting this issue that when there're more than 10 items in ordered list and we want to export the Markdown file to PDF, the first digit of the index seem to be hidden.

To reproduce, suppose we create a markdown file like this:

```markdown
1. a
2. b
3. c
4. d
5. e
6. f
7. g
8. h
9. i
10. j
11. k
```

It shows perfectly in the editor and the exported HTML. However, when we export it to PDF, we got:

![image](https://user-images.githubusercontent.com/32540679/170077961-6b1b0495-7251-477c-b3be-8d8e9c6347a5.png)

> The color of index is blue because I've changed the color theme.

I believe this is related to insufficient width, so I modified the `padding-left` attribute of `ol` to `2em`, which works as expected as a workaround. I wonder if there's anything better we can do.

**Comment by andredelft** [comment]
Hi @SignorMercurio,

Great catch, thanks for sharing. If you look closely in the editor, you can see that all the tens digit exceeds list container in the Typora editor, as illustrated below (using the inspector):

<img width="653" alt="Schermafbeelding 2022-05-26 om 15 48 51" src="https://user-images.githubusercontent.com/32297879/170500957-a0177f20-7ffc-4b86-b3f7-59fa483f378d.png">

I believe this is the reason that it is cut off from the PDF export (though I do not know its inner workings).

Unfortunately, I cannot do anything about this: the list counters exceeding the list container is expected behaviour, which you can replicate by making long lists in the [Tailwind workspace](https://play.tailwindcss.com/uj1vGACRJA). And also note that it also happens in other themes as well, though most of the time you have to go further than 10 items: try making a 1000 item list in the GitHub theme, you'll find the same issue in the PDF export!

Since it is a Typora issue, you could try submitting an issue here: https://github.com/typora/typora-issues. And for a work-around, increasing the padding left seems an excellent idea to me. If you want to make sure you're not targeting nested lists, you can use this selector in your custom CSS:

```css
#write > ol {
   padding-left: 2em;
}
```

**Comment by andredelft** [comment]
@SignorMercurio just thought of another solution that might be interesting for you. You can also use `list-style-position` to solve your problem:

```css
ol {
  list-style-position: inside;
}
```

See also the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position). You can use this in combination with `padding-left: 0` to properly align the items to the left.

I think it has other layout drawbacks which I don't really like, but it at least guarantees that everything will be contained in the list container!
