### ISSUE TITLE
Suggestion: Improve padding and styling on input box

### ISSUE THREAD

**Issue by comanche** [andredelft/typora-tailwind-theme#9]
Improve the padding and styling on the input box as shown below:

**Current**

![current](https://user-images.githubusercontent.com/1100167/161841344-74d29a3f-a3aa-4f56-a129-23c07be90a6b.png)

**With Padding**

![after](https://user-images.githubusercontent.com/1100167/161841148-1de82c7b-02ca-4927-b295-79e88a100461.png)

**Comment by andredelft** [comment]
Hi @comanche,

Thanks for your suggestion! I like it, though I found that increasing the padding on the search bar(s) is a bit difficult, since the height of the search modal is hardcoded in the original CSS. Since this is done for a lot of different cases (search, search and replace, search and replace with status message, search in seamless mode, etc...), it becomes a bit tedious and error-prone to change it, so I decided to leave it as it is.

I did however use the opportunity to change other things on the search modal, like the button style, rounded input corners and the drop shadow. Please refer to the latest release: https://github.com/andredelft/typora-tailwind-theme/releases/tag/v1.1.2. Hope you like it!

Best,

André
